package com.tradeapp.movingAverageBuy.writer;

import org.springframework.batch.item.ItemWriter;

import java.util.List;

public class DummyWriter<T> implements ItemWriter<T> {

    @Override
    public void write(List<? extends T> list) throws Exception {
        // just an autogenerated stub.
    }
}
